- charts:
  - clusters:
    - demo-cluster-1
    configuration:
      values:
        ClientCpuLimits: 100m
        ClientCpuRequests: 25m
        ClientHeapSize: 128m
        ClientMemoryLimits: 512Mi
        ClientMemoryRequests: 256Mi
        ClientReplicas: 2
        Component: elasticsearch
        DataCpuLimits: "1"
        DataCpuRequests: 250m
        DataHeapSize: 1536m
        DataMemoryLimits: 4Gi
        DataMemoryRequests: 2Gi
        DataReplicas: 3
        DataStorage: 30Gi
        DataStorageClass: anything
        DataStorageClassVersion: alpha
        Image: jetstack/elasticsearch-pet:2.3.5
        ImagePullPolicy: Always
        MasterCpuLimits: 100m
        MasterCpuRequests: 25m
        MasterHeapSize: 128m
        MasterMemoryLimits: 512Mi
        MasterMemoryRequests: 256Mi
        MasterReplicas: 2
        Name: es
    name: elasticsearch-1
    src: https://github.com/iljapoletaev/ku_test/elastic
    version: 0.1.2
  - clusters:
    - demo-cluster-1
    configuration:
      values:
        storage: default
    name: styles-transf-1
    src: https://github.com/kuberlab-catalog/styles-transfer-v2/
    version: 1.0.0
  name: asdasd
- charts:
  - clusters:
    - demo-cluster-1
    configuration:
      values:
        ClientCpuLimits: 100m
        ClientCpuRequests: 25m
        ClientHeapSize: 128m
        ClientMemoryLimits: 512Mi
        ClientMemoryRequests: 256Mi
        ClientReplicas: 2
        Component: elasticsearch
        DataCpuLimits: "1"
        DataCpuRequests: 250m
        DataHeapSize: 1536m
        DataMemoryLimits: 4Gi
        DataMemoryRequests: 2Gi
        DataReplicas: 3
        DataStorage: 30Gi
        DataStorageClass: anything
        DataStorageClassVersion: alpha
        Image: jetstack/elasticsearch-pet:2.3.5
        ImagePullPolicy: Always
        MasterCpuLimits: 100m
        MasterCpuRequests: 25m
        MasterHeapSize: 128m
        MasterMemoryLimits: 512Mi
        MasterMemoryRequests: 256Mi
        MasterReplicas: 2
        Name: es
    name: elasticsearch-1
    src: https://github.com/iljapoletaev/ku_test/elastic
    version: 0.1.2
  name: elast
- charts:
  - clusters:
    - demo-cluster-1
    configuration:
      values:
        ClientCpuLimits: 100m
        ClientCpuRequests: 25m
        ClientHeapSize: 128m
        ClientMemoryLimits: 512Mi
        ClientMemoryRequests: 256Mi
        ClientReplicas: 2
        Component: elasticsearch
        DataCpuLimits: "1"
        DataCpuRequests: 250m
        DataHeapSize: 1536m
        DataMemoryLimits: 4Gi
        DataMemoryRequests: 2Gi
        DataReplicas: 3
        DataStorage: 30Gi
        DataStorageClass: anything
        DataStorageClassVersion: alpha
        Image: jetstack/elasticsearch-pet:2.3.5
        ImagePullPolicy: Always
        MasterCpuLimits: 100m
        MasterCpuRequests: 25m
        MasterHeapSize: 128m
        MasterMemoryLimits: 512Mi
        MasterMemoryRequests: 256Mi
        MasterReplicas: 2
        Name: es
    name: elasticsearch-1
    src: https://github.com/iljapoletaev/ku_test/elastic
    version: 0.1.2
  name: elastic
- charts:
  - clusters:
    - demo-cluster-1
    configuration:
      values:
        ClientCpuLimits: 100m
        ClientCpuRequests: 25m
        ClientHeapSize: 128m
        ClientMemoryLimits: 512Mi
        ClientMemoryRequests: 256Mi
        ClientReplicas: 2
        Component: elasticsearch
        DataCpuLimits: "1"
        DataCpuRequests: 250m
        DataHeapSize: 1536m
        DataMemoryLimits: 4Gi
        DataMemoryRequests: 2Gi
        DataReplicas: 3
        DataStorage: 30Gi
        DataStorageClass: anything
        DataStorageClassVersion: alpha
        Image: jetstack/elasticsearch-pet:2.3.5
        ImagePullPolicy: Always
        MasterCpuLimits: 100m
        MasterCpuRequests: 25m
        MasterHeapSize: 128m
        MasterMemoryLimits: 512Mi
        MasterMemoryRequests: 256Mi
        MasterReplicas: 2
        Name: es
    name: elasticsearch-3
    src: https://github.com/iljapoletaev/ku_test/elastic
    version: 0.1.2
  name: aaaaaaa
- charts:
  - clusters:
    - minikube
    - demo-cluster-1
    configuration:
      values:
        ClientCpuLimits: 100m
        ClientCpuRequests: 25m
        ClientHeapSize: 128m
        ClientMemoryLimits: 512Mi
        ClientMemoryRequests: 256Mi
        ClientReplicas: 2
        Component: elasticsearch
        DataCpuLimits: "1"
        DataCpuRequests: 250m
        DataHeapSize: 1536m
        DataMemoryLimits: 4Gi
        DataMemoryRequests: 2Gi
        DataReplicas: 3
        DataStorage: 30Gi
        DataStorageClass: anything
        DataStorageClassVersion: alpha
        Image: jetstack/elasticsearch-pet:2.3.5
        ImagePullPolicy: Always
        MasterCpuLimits: 100m
        MasterCpuRequests: 25m
        MasterHeapSize: 128m
        MasterMemoryLimits: 512Mi
        MasterMemoryRequests: 256Mi
        MasterReplicas: 2
        Name: es
    name: elasticsearch-3
    src: https://github.com/iljapoletaev/ku_test/elastic
    version: 0.1.2
  name: sassssss
- charts:
  - clusters:
    - demo-cluster-1
    configuration:
      values:
        ClientCpuLimits: 100m
        ClientCpuRequests: 25m
        ClientHeapSize: 128m
        ClientMemoryLimits: 512Mi
        ClientMemoryRequests: 256Mi
        ClientReplicas: 2
        Component: elasticsearch
        DataCpuLimits: "1"
        DataCpuRequests: 250m
        DataHeapSize: 1536m
        DataMemoryLimits: 4Gi
        DataMemoryRequests: 2Gi
        DataReplicas: 3
        DataStorage: 30Gi
        DataStorageClass: anything
        DataStorageClassVersion: alpha
        Image: jetstack/elasticsearch-pet:2.3.5
        ImagePullPolicy: Always
        MasterCpuLimits: 100m
        MasterCpuRequests: 25m
        MasterHeapSize: 128m
        MasterMemoryLimits: 512Mi
        MasterMemoryRequests: 256Mi
        MasterReplicas: 2
        Name: es
    name: elasticsearch-3
    src: https://github.com/iljapoletaev/ku_test/elastic
    version: 0.1.2
  name: aaaaa
- charts:
  - clusters:
    - demo-cluster-1
    configuration:
      values:
        storage: default
    name: styles-transf-1
    src: https://github.com/kuberlab-catalog/styles-transfer-v2/
    version: 1.0.0
  name: atest
- charts:
  - clusters:
    - demo-cluster-1
    configuration:
      values:
        storage: default
    name: styles-transf-1
    src: https://github.com/kuberlab-catalog/styles-transfer-v2/
    version: 1.0.0
  name: aaaaaaaaaaa
