- charts:
  - clusters:
    - minikube
    configuration:
      values:
        image: wernight/codiad:alpine
        persistence:
          accessMode: ReadWriteMany
          enabled: true
          nfs:
            codiadPath: codiad
            path: /exports
            server: 10.0.0.0
          size: 16Gi
          storageClass: standard
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        serviceType: ClusterIP
    name: codiad
    src: https://github.com/kuberlab-catalog/codiad/
    version: 1.0.1
  name: codiad-pb
