- charts:
  - clusters:
    - minikube
    configuration: {}
    name: grafana-prometheus
    src: https://github.com/kuberlab-catalog/grafana-prometheus/chart/
    version: 1.0.1
  - clusters:
    - minikube
    configuration: {}
    name: grafana-prometheus
    src: https://github.com/kuberlab-catalog/grafana-prometheus/chart/
    version: 1.0.1
  name: mon
- charts:
  - clusters:
    - minikube
    configuration:
      values:
        cpu:
          limits: 8000m
          requests: 100m
        image:
          Name: lsheiba/fast-neural-style
          Tag: latest
        memory:
          limits: 16Gi
          requests: 64Mi
        persistence:
          accessMode: ReadWriteMany
          enabled: true
          nfs:
            path: /kuberlab
            server: 192.168.1.55
          size: 16Gi
          storageClass: standard
        replicas: 1
        serviceType: ClusterIP
    name: fast-neural-style
    src: https://github.com/lsheiba/fast-neural-style/
    version: 1.0.0
  name: fast
- charts:
  - clusters:
    - minikube
    configuration:
      values:
        cpu:
          limits: 8000m
          requests: 100m
        image:
          Name: lsheiba/tf-jupyter-devel-gpu
          Tag: latest
        memory:
          limits: 16Gi
          requests: 4Gi
        persistence:
          accessMode: ReadWriteMany
          enabled: true
          nfs:
            path: /kuberlab/fast
            server: 192.168.1.55
          size: 16Gi
          storageClass: standard
        replicas: 1
        serviceType: ClusterIP
    name: tensorflow-jupyter-gpu
    src: https://github.com/lsheiba/tensorflow-jupyter-gpu/
    version: 1.0.0
  name: tfgpu-1
