- charts:
  - clusters:
    - minikube
    configuration: {}
    name: grafana-prometheus
    src: https://github.com/kuberlab-catalog/grafana-prometheus/chart/
    version: 1.0.1
  - clusters:
    - minikube
    configuration: {}
    name: grafana-prometheus
    src: https://github.com/kuberlab-catalog/grafana-prometheus/chart/
    version: 1.0.1
  name: mon
- charts:
  - clusters:
    - demo-cluster-2
    configuration:
      values:
        Component: tensorflow-inception
        ContainerPort: 9090
        Image: quay.io/lachie83/inception_serving
        ImagePullPolicy: IfNotPresent
        ImageTag: latest
        Replicas: 1
        Resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        ServicePort: 9090
        ServiceType: LoadBalancer
    name: tensorflow-inception
    src: https://github.com/lsheiba/charts/incubator/tensorflow-inception
    version: 0.1.1
  name: fst
- charts:
  - clusters:
    - demo-cluster-2
    configuration:
      values:
        cpu:
          limits: 8000m
          requests: 100m
        image:
          Name: lsheiba/fast-neural-style
          Tag: latest
        memory:
          limits: 16Gi
          requests: 64Mi
        persistence:
          accessMode: ReadWriteMany
          enabled: true
          nfs:
            path: /kuberlab
            server: 192.168.1.55
          size: 16Gi
          storageClass: standard
        replicas: 1
        serviceType: ClusterIP
    name: fast-neural-style
    src: https://github.com/lsheiba/fast-neural-style/
    version: 1.0.0
  name: fast
