- charts:
  - clusters:
    - minikube
    configuration: {}
    name: grafana-prometheus
    src: https://github.com/kuberlab-catalog/grafana-prometheus/chart/
    version: 1.0.1
  - clusters:
    - minikube
    configuration: {}
    name: grafana-prometheus
    src: https://github.com/kuberlab-catalog/grafana-prometheus/chart/
    version: 1.0.1
  name: mon
- charts:
  - clusters:
    - demo-cluster-2
    configuration:
      values:
        Component: tensorflow-inception
        ContainerPort: 9090
        Image: quay.io/lachie83/inception_serving
        ImagePullPolicy: IfNotPresent
        ImageTag: latest
        Replicas: 1
        Resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        ServicePort: 9090
        ServiceType: LoadBalancer
    name: tensorflow-inception
    src: https://github.com/lsheiba/charts/incubator/tensorflow-inception
    version: 0.1.1
  name: fst
